apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustercelvalidationpolicies.policy.example.com
spec:
  group: policy.example.com
  scope: Cluster
  names:
    plural: clustercelvalidationpolicies
    singular: clustercelvalidationpolicy
    kind: ClusterCelValidationPolicy
    shortNames:
      - ccvp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                match:
                  type: object
                  properties:
                    resources:
                      type: array
                      items:
                        type: string
                    operations:
                      type: array
                      items:
                        type: string
                validations:
                  type: array
                  items:
                    type: object
                    properties:
                      expression:
                        type: string
                      enforcement:
                        type: string
                      messageExpression:
                        type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacecelvalidationpolicies.policy.example.com
spec:
  group: policy.example.com
  scope: Namespaced
  names:
    plural: namespacecelvalidationpolicies
    singular: namespacecelvalidationpolicy
    kind: NamespaceCelValidationPolicy
    shortNames:
      - ncvp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                match:
                  type: object
                  properties:
                    resources:
                      type: array
                      items:
                        type: string
                    operations:
                      type: array
                      items:
                        type: string
                validations:
                  type: array
                  items:
                    type: object
                    properties:
                      expression:
                        type: string
                      enforcement:
                        type: string
                      messageExpression:
                        type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustercelmutationpolicies.policy.example.com
spec:
  group: policy.example.com
  scope: Cluster
  names:
    plural: clustercelmutationpolicies
    singular: clustercelmutationpolicy
    kind: ClusterCelMutationPolicy
    shortNames:
      - ccmp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                match:
                  type: object
                  properties:
                    resources:
                      type: array
                      items:
                        type: string
                    operations:
                      type: array
                      items:
                        type: string
                labels:
                  type: object
                  additionalProperties:
                    type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacecelmutationpolicies.policy.example.com
spec:
  group: policy.example.com
  scope: Namespaced
  names:
    plural: namespacecelmutationpolicies
    singular: namespacecelmutationpolicy
    kind: NamespaceCelMutationPolicy
    shortNames:
      - ncmp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                match:
                  type: object
                  properties:
                    resources:
                      type: array
                      items:
                        type: string
                    operations:
                      type: array
                      items:
                        type: string
                labels:
                  type: object
                  additionalProperties:
                    type: string
