apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-webhook
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-webhook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
rules:
  - apiGroups:
      - policy.example.com
    resources:
      - clustercelvalidationpolicies
      - namespacecelvalidationpolicies
      - clustercelmutationpolicies
      - namespacecelmutationpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-webhook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
subjects:
  - kind: ServiceAccount
    name: policy-webhook
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: policy-webhook
  apiGroup: rbac.authorization.k8s.io

