# custom-api-loca-deploy.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-api-local-sa
  namespace: custom-api-local-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-api-local-dep
  namespace: custom-api-local-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-api-server
  template:
    metadata:
      labels:
        app: custom-api-server
    spec:
      serviceAccountName: custom-api-local-sa
      containers:
      - name: custom-api
        image: <docker image>
        ports:
        - containerPort: 8443
        env:
        - name: NAMESPACE_TEAM_LABEL
          value: "team"
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        - name: proxy-ca
          mountPath: /ca/front-proxy-ca.crt
          subPath: ca.crt
          readOnly: true
        livenessProbe:
          exec:
            command:
            - python3
            - -c
            - |
              import requests
              r = requests.get(
                  "https://localhost:8443/healthz",
                  cert=("/tls/tls.crt", "/tls/tls.key"),
                  verify="/ca/front-proxy-ca.crt"
              )
              assert r.status_code == 200
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python3
            - -c
            - |
              import requests
              r = requests.get(
                  "https://localhost:8443/healthz",
                  cert=("/tls/tls.crt", "/tls/tls.key"),
                  verify="/ca/front-proxy-ca.crt"
              )
              assert r.status_code == 200
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: tls
        secret:
          secretName: custom-api-tls
      - name: proxy-ca
        secret:
          secretName: proxy-ca-secret
---
apiVersion: v1
kind: Service
metadata:
  name: custom-api-local-svc
  namespace: custom-api-local-ns
spec:
  selector:
    app: custom-api-server
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-api-local-namespace-reader
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-api-local-namespace-reader-binding
subjects:
- kind: ServiceAccount
  name: custom-api-local-sa
  namespace: custom-api-local-ns
roleRef:
  kind: ClusterRole
  name: custom-api-local-namespace-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.custom.api.local
spec:
  service:
    name: custom-api-local-svc
    namespace: custom-api-local-ns
  group: custom.api.local
  version: v1
  caBundle: < base64 of /etc/kubernetes/pki/front-proxy-ca.crt > 
  groupPriorityMinimum: 2000
  versionPriority: 10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subjectaccessreview-runner
rules:
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subjectaccessreview-runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subjectaccessreview-runner
subjects:
- kind: ServiceAccount
  name: custom-api-local-sa
  namespace: custom-api-local-ns
